// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/ledger/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLedgerEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerEntriesRequest) Reset() {
	*x = CreateLedgerEntriesRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerEntriesRequest) ProtoMessage() {}

func (x *CreateLedgerEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerEntriesRequest.ProtoReflect.Descriptor instead.
func (*CreateLedgerEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLedgerEntriesRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateLedgerEntriesRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateLedgerEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerEntriesResponse) Reset() {
	*x = CreateLedgerEntriesResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerEntriesResponse) ProtoMessage() {}

func (x *CreateLedgerEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerEntriesResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLedgerEntriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ledger_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ledger/ledger.proto\x12\x06ledger\"[\n" +
	"\x1aCreateLedgerEntriesRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"7\n" +
	"\x1bCreateLedgerEntriesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2o\n" +
	"\rLedgerService\x12^\n" +
	"\x13CreateLedgerEntries\x12\".ledger.CreateLedgerEntriesRequest\x1a#.ledger.CreateLedgerEntriesResponseB\x10Z\x0e./proto/ledgerb\x06proto3"

var (
	file_proto_ledger_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_ledger_proto_rawDescData []byte
)

func file_proto_ledger_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_ledger_proto_rawDescData
}

var file_proto_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ledger_ledger_proto_goTypes = []any{
	(*CreateLedgerEntriesRequest)(nil),  // 0: ledger.CreateLedgerEntriesRequest
	(*CreateLedgerEntriesResponse)(nil), // 1: ledger.CreateLedgerEntriesResponse
}
var file_proto_ledger_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.LedgerService.CreateLedgerEntries:input_type -> ledger.CreateLedgerEntriesRequest
	1, // 1: ledger.LedgerService.CreateLedgerEntries:output_type -> ledger.CreateLedgerEntriesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ledger_ledger_proto_init() }
func file_proto_ledger_ledger_proto_init() {
	if File_proto_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_ledger_proto = out.File
	file_proto_ledger_ledger_proto_goTypes = nil
	file_proto_ledger_ledger_proto_depIdxs = nil
}
